language: node_js
node_js:
- '8'
addons:
  apt:
    update: true
cache:
  directories:
  - node_modules
install:
- npm install
script:
- git init
- git config --local  user.name "Yuying Wu"
- git config --local  user.email "wuyuying1128@gmail.com"
- npm run deploy
after_success:
- echo -e "deploy success!!!"
branches:
  only:
  - gatsby-master
  - dev
  - gatsby-output
  - gatsby
env:
  global:
  - GH_REF: github.com/YuyingWu/blog.git
  - secure: eTOXeE1g5EIaa03l01vbhwjV2v6O3hTcYnZTMm11R2uUShEiiUVOcuatx8y32G09TK0emXZ3uo8JuXF+RhxiLFYsrOAnaNLOW0yOTFmc6UKSjMiqfT78Uv2wG51SWFMLeWLvs7uQ5T9xwRx60yzw1hH8tX/oz7/vGVe8LafQIT8y5fPMtLhfN/pxvc0Ef/SQeHZ7NvO1UJH3vlDL7KYjvczZRUkH10qiRBRdLwUumkHA39oMeZ+jYzlA7wG4zWCAQTHq9Dfr9cTzZKwQf6yOll2G22ABDSckQHLPNUsoYvm4PUB9qSTPuvMkNLvKRecRbTz7ij5SqC3BVSwRvnuIueQkfqaDQUDteRudEKgA6DyHIoKh0epFBwpnrXxdpueA7tygarCt9l0fWsTD1gPhWGn8wnPOJJAkH9LycPL2mgLYZbLPwkqA885GO+SvMg0n4eqGco823/L4xF3oCo5k58NoR9CNItXIQLLrlOzl2dTz1xIyxiV11Gx9+QI97VjRPY8bCtZb0aoCt2b2KwCs/8UZi8W7lbrBOUw1fvEPx0zrDePjvInG06ZoBt9nf7LigIUgT1yymkMqdgPCxEknq7iVGW4a+SP+2g80rvHaCJbHsENhfYOrenT8suqq70ubUb3H+ySALaX3j0a3Z6tR+/5IbmBU2s2L4QWG2N3Q894=
before_install:
- openssl aes-256-cbc -K $encrypted_3cf6c1fd150f_key -iv $encrypted_3cf6c1fd150f_iv
  -in qq_rsa.enc -out ~/.ssh/qq_rsa -d
