language: node_js
node_js: stable

addons:
  apt:
    update: true

# Travis-CI Caching
cache:
  directories:
    - node_modules

# S: Build Lifecycle
install:
  - npm install

before_script:
 # - npm install -g gulp

script:
  - hexo g

after_script:
  # - hexo d

branches:
  only:
    - dev