language: node_js
node_js:
  - "8"
addons:
  apt:
    update: true
cache:
  directories:
  - node_modules
  # - public/build
  # - public/css
  # - public/js
  # - public/fancybox
  # - public/dist
  # - public/lib
install:
# - npm install
script:
# - npm run deploy
after_success:
 - echo -e "hello, travis"
# - cd ./public
# - git init
# - git config user.name "Yuying Wu"
# - git config user.email "wuyuying1128@gmail.com"
# - git add .
# - git commit -m "Update site"
# - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages
# - scp -o stricthostkeychecking=no -r ./* root@138.68.161.48:/home/wyyGatsby/
branches:
  only:
  - gastby-master
  - dev
env:
  global:
  - GH_REF: github.com/YuyingWu/blog.git
  - secure: JrIweNd41qceQfloL1BbAl1XdjZb19Kd/GQFTuKUHMMJvhVkbYJokoY8ieMb1kRZZfyF3z5YjLr0nQG4HtlRWdR0pOmmTNqK1Fdgk7e+K5HVxcaLKOz0GqrT+qY3px3R4NwU6MKPoTbkY2Mp4FDpP7pNqioKk1RXwNKzOkfKl5eAXvu3/9DZorKSZTLBl64sAzIF09VWh0vP/Q6+97sOnJEI/qvCdp3K2NOkFE6B9OPEV9xDfdtASkB3ThpMd+QiHcCj1veAs4QXrSPgjzYmA1VP99WF7nz/EApraAsI2mrgOMdy7w/mVQaHqvcAAMQEIrx58ZTWLJIuGP9NF3v26+msPnAkcw8COR3v1M/tDmgM3Yb1ome8clrSmKpK+DnoX7mukdtDIFrUgJNo5KGKeLmcJSUIvyIN1FZWxzM60UD10vSQtGvmSFOXLGCdatYPGtPOQvjjklsv3yfe1Ixug8pD28TGR05LMqEjg+lK/NAjDUCOudRft5QWTF9pTPVracq2H8eqYFoaykkZ6IPBMslFCnNNcrlgJgTNvf1if988SX10ApiLxFEGbmrEDzGo448nZ6MU17srY8vA3jKKKBlstjwJcYhXfpcUX4JUyHGshNOGyRxNTCqesg9oYlMZiVZtx6w5lvfAD2fGogs3WfMAwcyXCV/6vpKOFBb3JxQ=
before_install:
- openssl aes-256-cbc -K $encrypted_3cf6c1fd150f_key -iv $encrypted_3cf6c1fd150f_iv
  -in qq_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host 138.68.161.48\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config 


# language: node_js
# node_js:
#   - "8"
# addons:
#   apt:
#     update: true
# cache:
#   directories:
#   - node_modules
#   - public/build
#   - public/css
#   - public/js
#   - public/fancybox
#   - public/dist
#   - public/lib
# install:
# - npm install
# script:
# - hexo g
# after_success:
# - cd ./public
# - git init
# - git config user.name "Yuying Wu"
# - git config user.email "wuyuying1128@gmail.com"
# - git add .
# - git commit -m "Update site"
# - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages
# - scp -o stricthostkeychecking=no -r ./* root@138.68.161.48:/home/wyyNode/public/blog/
# branches:
#   only:
#   - dev
# env:
#   global:
#   - GH_REF: github.com/YuyingWu/blog.git
#   - secure: JrIweNd41qceQfloL1BbAl1XdjZb19Kd/GQFTuKUHMMJvhVkbYJokoY8ieMb1kRZZfyF3z5YjLr0nQG4HtlRWdR0pOmmTNqK1Fdgk7e+K5HVxcaLKOz0GqrT+qY3px3R4NwU6MKPoTbkY2Mp4FDpP7pNqioKk1RXwNKzOkfKl5eAXvu3/9DZorKSZTLBl64sAzIF09VWh0vP/Q6+97sOnJEI/qvCdp3K2NOkFE6B9OPEV9xDfdtASkB3ThpMd+QiHcCj1veAs4QXrSPgjzYmA1VP99WF7nz/EApraAsI2mrgOMdy7w/mVQaHqvcAAMQEIrx58ZTWLJIuGP9NF3v26+msPnAkcw8COR3v1M/tDmgM3Yb1ome8clrSmKpK+DnoX7mukdtDIFrUgJNo5KGKeLmcJSUIvyIN1FZWxzM60UD10vSQtGvmSFOXLGCdatYPGtPOQvjjklsv3yfe1Ixug8pD28TGR05LMqEjg+lK/NAjDUCOudRft5QWTF9pTPVracq2H8eqYFoaykkZ6IPBMslFCnNNcrlgJgTNvf1if988SX10ApiLxFEGbmrEDzGo448nZ6MU17srY8vA3jKKKBlstjwJcYhXfpcUX4JUyHGshNOGyRxNTCqesg9oYlMZiVZtx6w5lvfAD2fGogs3WfMAwcyXCV/6vpKOFBb3JxQ=
# before_install:
# - openssl aes-256-cbc -K $encrypted_3cf6c1fd150f_key -iv $encrypted_3cf6c1fd150f_iv
#   -in qq_rsa.enc -out ~/.ssh/id_rsa -d
# - chmod 600 ~/.ssh/id_rsa
# - echo -e "Host 138.68.161.48\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config 
