language: node_js
node_js: stable

# Travis-CI Caching
cache:
  directories:
    - node_modules
    - themes/fresh

# S: Build Lifecycle
install:
  - npm install
  - git clone https://github.com/YuyingWu/hexo-theme-fresh.git themes/fresh

before_script:
 # - npm install -g gulp

script:
  - hexo g

after_script:
  # - hexo d

branches:
  only:
    - dev