# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 小伍
homepage: /
subtitle: 
description: 小伍的自留地
author: Yuying Wu
language: zh-CN
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://wuyuying.com
root: /blog/
permalink: archives/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: 
- node_modules
- theme/fresh/node_modules

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 15
pagination_dir: page

index_generator_plus:
  per_page: 15

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: fresh

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git  
  repo: https://github.com/YuyingWu/blog.git
  branch: gh-pages

# site map
sitemap:
  path: sitemap.xml

# baidu sitemap, don't change the tab space of `path`
baidusitemap:
path: baidusitemap.xml

# search
# search:
#   path: search.xml
#   field: post
#   format: html
#   limit: 999

restful:
  # site 可配置为数组选择性生成某些属性
  # site: ['title', 'subtitle', 'description', 'author', 'since', email', 'favicon', 'avatar']
  site: true        # hexo.config mix theme.config
  posts_size: 0    # 文章列表分页，0 表示不分页
  posts_props:      # 文章列表项的需要生成的属性
    title: true
    slug: true
    date: true
    updated: true
    comments: true
    path: true
    excerpt: false
    cover: true      # 封面图，取文章第一张图片
    content: true
    keywords: false
    categories: true
    tags: true
  categories: false  # 分类数据
  tags: false        # 标签数据
  post: false        # 文章数据
  pages: false      # 额外的 Hexo 页面数据, 如 About
