<section class="post__meta">
	<a href="/blog/donate.html" title="码字辛苦求打赏" class="u-clearfix wgt-shield">
		<span class="title">Donate</span>
		<span class="desc">￥￥￥</span>
	</a>

	<a href="http://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank" 
		title="知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议" class="u-clearfix wgt-shield">
		<span class="title">License</span>
		<span class="desc">CC BY-NC-SA</span>
	</a>
</section>